import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "./providers";
import Head from "next/head";
import { Nav } from "./Layout/Nav/Nav";
import { Footer } from "./Layout/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={` antialiased flex flex-col`}>
        <Providers>
          <Nav />
          <div className="mt-[68px] min-h-[100vh]">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
